import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateTranslateBanner1616148972467 implements MigrationInterface {
  name = 'updateTranslateBanner1616148972467';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "banner" ADD "language_id" uuid NOT NULL`);
    await queryRunner.query(`ALTER TABLE "banner" ADD "code" character varying NOT NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "agent"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "agent"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "author"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "author"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "banner"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "banner"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "branch"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "branch"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "career"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "career"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "category"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "category"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "country"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "country"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "customer"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "customer"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "document"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "document"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "employee"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "employee"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "label"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "label"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "language"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "language"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission_role"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission_role"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_author"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_author"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_category"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_category"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_label"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_label"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "role"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "role"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "video"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "video"."updated_at" IS NULL`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`COMMENT ON COLUMN "video"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "video"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "solution"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "role"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "role"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_label"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_label"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_category"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_category"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_author"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource_author"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "resource"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission_role"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission_role"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "permission"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "language"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "language"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "label"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "label"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market_image"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market_image"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "focused_market"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "employee"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "employee"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "document"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "document"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "customer"."updatedAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "customer"."createdAt" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "country"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "country"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "category"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "category"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "career"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "career"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "branch"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "branch"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "banner"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "banner"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "author"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "author"."created_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "agent"."updated_at" IS NULL`);
    await queryRunner.query(`COMMENT ON COLUMN "agent"."created_at" IS NULL`);
    await queryRunner.query(`ALTER TABLE "banner" DROP COLUMN "code"`);
    await queryRunner.query(`ALTER TABLE "banner" DROP COLUMN "language_id"`);
  }
}
